Output demo.gif
Set Width 1000
Set Height 1000
Set LineHeight 1.3
Set PlaybackSpeed 0.8 # Make output 2 times slower


Env ANTHROPIC_API_KEY ""


Set Shell zsh
Sleep 0.5s
Type "./agent"
Enter
Sleep 1.5s
Type "n"
Type "ǐ "
Type "h"
Sleep 1.5s
Type "ǎo Claude!"
Enter
Sleep 8s
Type "wǒ xiǎng "
Type "he boba tea "
Sleep 1s
Type "🧋"
Enter
Sleep 8.5s
Sleep 7s
Type "Thanks for making that flashcard. Talk to you later Claude, Zai Jian!"
Enter
Sleep 10s
